# Generated by Django 3.2.4 on 2021-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo5',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.FileField(upload_to='sous_cat/icons', verbose_name='icon de la Catégorie'),
        ),
    ]
