# Generated by Django 3.2.4 on 2021-06-17 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.CreateModel(
            name='TreeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=150, verbose_name='URL')),
                ('icon', models.FileField(upload_to='sous_cat/icons', verbose_name='icon de la Catégorie')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='main.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Branche de Catégorie',
                'verbose_name_plural': 'Branches de Catégorie',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='main.treecategory', verbose_name='Branche de Catégorie'),
            preserve_default=False,
        ),
    ]
