# Generated by Django 3.2.4 on 2021-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210617_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top',
            field=models.BooleanField(default=True, verbose_name='Meilleur vente'),
        ),
    ]
