# Generated by Django 3.2.4 on 2021-07-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210624_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Catégorie', 'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Produit', 'verbose_name_plural': '4. Produits'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('id',), 'verbose_name': 'Sous Catégorie', 'verbose_name_plural': '3. Sous Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='treecategory',
            options={'ordering': ('id',), 'verbose_name': 'Branche de Catégorie', 'verbose_name_plural': '2. Branches de Catégorie'},
        ),
    ]
