# Generated by Django 3.2.4 on 2021-06-23 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance'),
            preserve_default=False,
        ),
    ]
